---
name: Check code base

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Run Lint on code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v5.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: false
          VALIDATE_MARKDOWN: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_YAML: false
          IGNORE_GITIGNORED_FILES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
