---
name: Unit Testing

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  unit_testing:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn install --immutable

      - name: Test project
        run: yarn test
